# General settings
experiment_name: "unet_resilient"
timestamp: ${now:%Y-%m-%d_%H-%M-%S}
seed: 42

# Training hyperparameters
hyperparameters:
  batch_size: 32
  num_epochs: 150
  learning_rate: 0.0001
  weight_decay: 0.0001

# Model config (new!)
model:
  init_features: 64
  dropout_rate: 0.3

# Optimizer settings
optimizer:
  type: "adam"

# Weights & Biases settings
wandb:
  entity: "AdvancedBA"
  project: "ForestSegmentationABA"
  mode: "online"
  save_model: true
  save_loss_plot: true

# Data settings
dataset:
  data_path: data/raw/Forest Segmented
  metadata_file: meta_data.csv
  roboflow_train_path: data/raw/roboflow/train
  roboflow_val_path: data/raw/roboflow/valid
  roboflow_test_path: data/raw/roboflow/test
  subset: false
  apply_augmentation: true
