program: src/advanced_ba_project/sweep.py
entity: AdvancedBA
project: ForestSegmentationABA
method: grid
name: sweep_with_dropout
metric:
  name: Val F1
  goal: maximize
parameters:
  batch_size:
    values: [16, 32]
  learning_rate:
    values: [0.001, 0.0001]
  weight_decay:
    values: [0.001, 0.0001]
  num_epochs:
    value: 100
  init_features:
    value: 64
  dropout_rate:
    values: [0.1, 0.2, 0.3]
  seed:
    value: 42
  apply_augmentation:
    values: [true, false]