name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip list
          pip install -e .

      - name: Run tests & coverage
        run: |
          $env:HYDRA_FULL_ERROR="1"; coverage run --source=advanced_ba_project -m pytest tests/; coverage report -m
        if: runner.os == 'Windows'
        shell: pwsh
      
      - name: Run tests & coverage
        run: |
          export HYDRA_FULL_ERROR=1
          coverage run --source=advanced_ba_project -m pytest tests/
          coverage report -m
        if: runner.os != 'Windows'
        
